# bunfig.toml
[build]
external = [
  "react",
  "react-dom",
  "react/jsx-runtime",
  "react/jsx-dev-runtime",

  "highlight.js",
  "rehype-highlight",
  "glob",
  "typescript",
  "typescript-json-schema",
  "@tanstack/react-query",
  "fsl-authorization",
  "vm2"
]

[test]
preload = ["./src/tests/setup.ts"]
