export const rootLayoutTemplate = `import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "PieUI Project",
  description: "Generated by PieUI.",
  applicationName: "PieUI Project",
  icons: {
    icon: "/favicon.ico",
    shortcut: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
`
